# -*- restclient -*-
#
GET http://localhost:3000/api

# Get people api
GET http://localhost:3000/api/people

# Get popular studio
GET http://localhost:3000/api/popular-studio

# POST person
POST http://localhost:3000/api/people
Content-Type: application/json

{ "first-name":"Fiona", "last-name": "Hobbs","films":[{"title":"Toy Story","studio":"Pixar","release-year":"1996"},
{"title":"Fifty Shades of Grey", "studio":"Paramount", "release-year":"2015"}]}

# POST another person
POST http://localhost:3000/api/people
Content-Type: application/json

{ "first-name":"Steve", "last-name": "Hobbs","films":[{"title":"Dune","studio":"Legendary","release-year":"2021"},
{"title":"Star Wars Rogue One", "studio":"Disney", "release-year":"2015"}]}

# GET stuff
GET http://localhost:3000/api/stuff
