name: Clojure CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein test

  deploy:
    runs-on: ubuntu-latest # Setup an environment to run the action
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    environment: production
    steps:
      - name: Hello World
        shell: bash
        run: |
          echo "Hello, World!"
